version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: nexus_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
