name: CI Pipeline

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate --schema=./apps/web/prisma/schema.prisma
      - name: Run ESLint
        run: npm run lint --workspace web

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate --schema=./apps/web/prisma/schema.prisma
      - name: TypeScript Check
        run: npm run check-types --workspace web

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      SKIP_DB_TESTS: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate --schema=./apps/web/prisma/schema.prisma
      - name: Run Tests
        run: npm run test:ci --workspace web

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate --schema=./apps/web/prisma/schema.prisma
      - name: Build Web
        run: npm run build --workspace web
        env:
          SKIP_ENV_VALIDATION: '1'

